import 'package:flutter/material.dart';
import './data.dart';
import 'dart:convert';
import 'package:http/http.dart' as http;

class AsmaulHusna extends StatefulWidget {
  @override
  _AsmaulHusnaState createState() => _AsmaulHusnaState();
}

class _AsmaulHusnaState extends State<AsmaulHusna> {
  var url =
      "http://api.aladhan.com/asmaAlHusna/1,2,3,4,5,6,7,8,910,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99";

  Autogenerated autogenerated;

  @override
  void initState() {
    // TODO: implement initState
    super.initState();

    dataApi();
  }

  PageController controller = PageController();

  dataApi() async {
    final res = await http.get(url);
    final jsonData = jsonDecode(res.body);

    autogenerated = Autogenerated.fromJson(jsonData);

    setState(() {});
  }

  @override
  Widget build(BuildContext context) {
    return autogenerated == null
        ? Center(child: CircularProgressIndicator())
        : PageView(
            scrollDirection: Axis.horizontal,
            controller: controller,
            children: autogenerated.data
                .map((d) => Container(
                      padding: EdgeInsets.all(50.0),
                      color: Colors.amber,
                      child: Card(
                        shape: RoundedRectangleBorder(
                            borderRadius: BorderRadius.circular(50.0)),
                        elevation: 20.0,
                        child: Container(
                          decoration: BoxDecoration(
                              borderRadius: BorderRadius.circular(10.0),
                              image: DecorationImage(
                                  image: NetworkImage(
                                      "https://ak7.picdn.net/shutterstock/videos/23010907/thumb/1.jpg"),
                                  fit: BoxFit.cover)),
                          padding: EdgeInsets.all(20.0),
                          height: 400.0,
                          width: 400.0,
                          child: Column(
                            children: <Widget>[
                              SizedBox(height: 100.0),
                              Text(d.name,
                                  style: TextStyle(
                                      fontWeight: FontWeight.bold,
                                      fontSize: 25.0)),
                              Text(d.transliteration,
                                  style: TextStyle(
                                      fontWeight: FontWeight.bold,
                                      fontSize: 20.0)),
                              Divider(),
                              Text(d.en.meaning,
                                  style: TextStyle(
                                      fontWeight: FontWeight.bold,
                                      fontSize: 18.0)),
                            ],
                          ),
                        ),
                      ),
                    ))
                .toList(),
          );
  }
}
